language: go

go:
  - 1.5

before_install:
  - go get github.com/ChrisTrenkamp/goxpath

script:
  - go test -coverprofile=coverage.txt -coverpkg=github.com/ChrisTrenkamp/goxpath/...

after_success:
  - bash <(curl -s https://codecov.io/bash)
